









/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],
  //vbaSidebar: [{type: 'autogenerated', dirName: 'vba'}]
};

module.exports = {
  tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],
}